name: Django CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and start DB
        run: |
          docker compose up -d --build db

      - name: Wait for DB to be ready
        run: |
          until docker compose exec db pg_isready -U postgres; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

      - name: Build web service
        run: docker compose build web

      - name: Run Django tests
        run: docker compose run --rm web python manage.py test

      - name: Shutdown services
        run: docker compose down -v
